### PR TITLE
Fix sxg_sig_test to allow variable-size sig.

### LINKED ISSUE #76: length of signature is not consistent
we are seeing inconsistencies in the length of the signature, which is causing intermittent failures in CI. I was also able to reproduce in the libsxg build environment by building and running `sxg_sig_test` repeatedly with this script:
```
attempts=0
fails=0
for i in `seq 1 500`; do
  attempts=$((attempts+1));
  make sxg_sig_test && ./sxg_sig_test
  fails=$((fails+$?))
done
echo $attempts && echo $fails
```

In both environments, the signature is occasionally 4 bytes shorter than expected. 

This is the output in our CI:

```
09:22:29 pinterest/filters/http/sxg/filter_test.cc:187: Failure
09:22:29 Expected equality of these values:
09:22:29   sxg.toString()
09:22:29     Which is: "sxg1-b3\0\0\x1Ehttps://example.org/hello.html\0\x1\x84\0\0\x84https://example.org/hello.html;cert-sha256=*unJ3rwJT2DwWlJAw1lfVLvPjeYoJh0+QUQ97zJQPZtc=*;cert-url=\"https://example.org/.well-known/amphtml/cert.cbor\";date=1610416640;expires=1611021440;integrity=\"digest/mi-sha256-03\";sig=*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%*;validity-url=\"https://example.org/.well-known/amphtml/validity.msg\"\xA4" "FdigestX9mi-sha256-03=0x0E2wkWVYOJ7Gq8+Kfaiyjo3gYCyaijhGGgkzjPoTo=G:statusC200Lcontent-typeItext/htmlPcontent-encodingLmi-sha256-03\0\0\0\0\0\0\x10\0<html><body>hi!</body></html>\n"
09:22:29   result
09:22:29     Which is: "sxg1-b3\0\0\x1Ehttps://example.org/hello.html\0\x1\x80\0\0\x84https://example.org/hello.html;cert-sha256=*unJ3rwJT2DwWlJAw1lfVLvPjeYoJh0+QUQ97zJQPZtc=*;cert-url=\"https://example.org/.well-known/amphtml/cert.cbor\";date=1610416640;expires=1611021440;integrity=\"digest/mi-sha256-03\";sig=*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%*;validity-url=\"https://example.org/.well-known/amphtml/validity.msg\"\xA4" "FdigestX9mi-sha256-03=0x0E2wkWVYOJ7Gq8+Kfaiyjo3gYCyaijhGGgkzjPoTo=G:statusC200Lcontent-typeItext/htmlPcontent-encodingLmi-sha256-03\0\0\0\0\0\0\x10\0<html><body>hi!</body></html>\n"
```

here is a sample of the output from building and running `sxg_sig_test` repeatedly:
```
...
[ RUN      ] SxgSig.ConstructAndRelease
[       OK ] SxgSig.ConstructAndRelease (0 ms)
[ RUN      ] SxgSig.MakeSignature
/home/papazian/code/libsxg/tests/sxg_sig_test.cc:69: Failure
Expected equality of these values:
  expected
    Which is: "testname;cert-sha256=*WrpTHrnR9I9Cj+cizXTozEZB+BnjQKkRe8kKgme4iLU=*;cert-url=\"https://cert.test/cert.cbor\";date=0;expires=0;integrity=\"digest/mi-sha256-03\";sig=*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%*;validity-url=\"https://cert.test/validity.msg\""
  sxg_test::BufferToString(output)
    Which is: "testname;cert-sha256=*WrpTHrnR9I9Cj+cizXTozEZB+BnjQKkRe8kKgme4iLU=*;cert-url=\"https://cert.test/cert.cbor\";date=0;expires=0;integrity=\"digest/mi-sha256-03\";sig=*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%*;validity-url=\"https://cert.test/validity.msg\""
[  FAILED  ] SxgSig.MakeSignature (1 ms)
[----------] 2 tests from SxgSig (1 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (1 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SxgSig.MakeSignature

 1 FAILED TEST
[ 31%] Built target gtest
[ 81%] Built target sxg
[ 90%] Built target test_util
...
[ RUN      ] SxgSig.MakeSignature
[       OK ] SxgSig.MakeSignature (1 ms)
[----------] 2 tests from SxgSig (1 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (1 ms total)
[  PASSED  ] 2 tests.
[ 31%] Built target gtest
[ 81%] Built target sxg
[ 90%] Built target test_util
[100%] Built target sxg_sig_test
Running main() from /home/papazian/code/libsxg/build/third_party/gtest/googletest/src/gtest_main.cc
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from SxgSig
[ RUN      ] SxgSig.ConstructAndRelease
[       OK ] SxgSig.ConstructAndRelease (0 ms)
[ RUN      ] SxgSig.MakeSignature
[       OK ] SxgSig.MakeSignature (1 ms)
[----------] 2 tests from SxgSig (1 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (1 ms total)
[  PASSED  ] 2 tests.
500
1
```

Is this expected? if so, can we update the libsxg tests to account for this inconsistency? that would provide a template for us to handle in our own tests.

### PR DESCRIPTION
**Pull request by twifkak**
The ECDSA signature is a DER-encoded pair of integers, which results in
variable length. Change the assertion to remove the signature rather than
filling with % chars, so that it's resilient to this.

In addition, add an assertion that the signature is correct, by hard-coding an
expected signed message and then making all the necessary OpenSSL calls.

This was tested with

```bash
$ (attempts=0; display_attempts () { echo Attempts: $attempts; }; trap display_attempts INT && make sxg_sig_test && while 
./sxg_sig_test; do attempts=$(($attempts+1)); done)
...
^CAttempts: 4652
```

Fixes #76.

/cc @cpapazian @rgs1 Can you verify this works against BoringSSL?

### CODE REVIEW

**Review by banaag — APPROVED** [review]

**Comment by rgs1** [comment]
@twifkak thanks for the quick return, unless @cpapazian beats me to it I can test drive this with our Envoy repo to see if boring is happy too.

**Comment by cpapazian** [comment]
I'm getting some errors building the new test with boringssl: ```
[ 91%] Building CXX object CMakeFiles/sxg_sig_test.dir/tests/sxg_sig_test.cc.o
/home/papazian/code/libsxg/tests/sxg_sig_test.cc: In function ‘void {anonymous}::sxg_base64decode(const sxg_buffer_t*, sxg_buffer_t*)’:
/home/papazian/code/libsxg/tests/sxg_sig_test.cc:60:25: error: ‘EVP_ENCODE_CTX_new’ was not declared in this scope
   EVP_ENCODE_CTX* ctx = EVP_ENCODE_CTX_new();
                         ^~~~~~~~~~~~~~~~~~
/home/papazian/code/libsxg/tests/sxg_sig_test.cc:60:25: note: suggested alternative: ‘EVP_ENCODE_CTX’
   EVP_ENCODE_CTX* ctx = EVP_ENCODE_CTX_new();
                         ^~~~~~~~~~~~~~~~~~
                         EVP_ENCODE_CTX
In file included from /home/papazian/code/libsxg/build/third_party/gtest/googletest/include/gtest/gtest.h:387:0,
                 from /home/papazian/code/libsxg/tests/sxg_sig_test.cc:24:
/home/papazian/code/libsxg/tests/sxg_sig_test.cc:64:39: error: cannot convert ‘size_t* {aka long unsigned int*}’ to ‘int*’ for argument ‘3’ to ‘int EVP_DecodeUpdate(EVP_ENCODE_CTX*, uint8_t*, int*, const uint8_t*, size_t)’
                              src->size),
                                       ^
```

looks like `EVP_EncodeInit` and related functions behave a little bit differently. see: https://commondatastorage.googleapis.com/chromium-boringssl-docs/base64.h.html#EVP_EncodeInit

**Comment by cpapazian** [comment]
if you want to build with boringssl locally, these are my steps:
1. checkout and build borinssl
2. (if you want to build tests ... this isn't needed for just the static lib) add the OPENSSL_LIBRARIES variable to CMakeLists.txt: `set (OPENSSL_LIBRARIES "OpenSSL::Crypto OpenSSL::SSL")`
3. run cmake with options for the boringssl static library: `cmake .. -DSXG_BUILD_SHARED=off -DSXG_BUILD_STATIC=on -DRUN_TEST=on -DSXG_WITH_CERT_CHAIN=off -DOPENSSL_CRYPTO_LIBRARY=../../boringssl/build/crypto/libcrypto.a -DOPENSSL_ROOT_DIR=../../boringssl/ -DOPENSSL_INCLUDE_DIR=../../boringssl/include`

happy to add these to docs  if you can point me to the right place. 

will also take a longer look to figure out the right way to set OPENSSL_LIBRARIES variable. i think maybe we want `OpenSSL::Crypto` instead of `${OPENSSL_LIBRARIES}` based on these docs: https://cmake.org/cmake/help/v3.6/module/FindOpenSSL.html

**Comment by cpapazian** [comment]
actually reading a bit more, i think you can just use `EVP_EncodeBlock` directly. i don't think you need to initialize the EVP context with `EVP_ENCODE_CTX_new`

File: tests/sxg_sig_test.cc [hunk 1]
```diff
@@ -26,13 +28,65 @@
...
+// a loop in test.
+void sxg_base64decode(const sxg_buffer_t* src, sxg_buffer_t* dst) {
+  const size_t offset = dst->size;
+  // 4-byte blocks to 3-byte, assuming none are padding chars; we'll adjust at
+  // the end.
+  const EVP_ENCODE_BLOCK_T estimated_out_length = 3 * (src->size / 4);
+
+  // EVP_DecodeBlock doesn't support padding chars, so we use the long form.
+  ASSERT_TRUE(sxg_buffer_resize(offset + estimated_out_length, dst));
+  EVP_ENCODE_CTX* ctx = EVP_ENCODE_CTX_new();
```
Comment (cpapazian) [inline tests/sxg_sig_test.cc:60]: as mentioned in comments, `EVP_ENCODE_CTX_new` is deprecated in BoringSSL. why can't we just use `EVP_EncodeBlock` directly?

**Review by cpapazian — CHANGES_REQUESTED** [review]

File: tests/sxg_sig_test.cc (hunk 1 above)
Comment (cpapazian) [reply tests/sxg_sig_test.cc:60]: I took another look at this, and I see what you mean regarding padding. When I was looking earlier, I was focused on the encode side. That said, I think we can strip the padding bytes manually. Something like this:
```
void sxg_base64decode(const sxg_buffer_t* src, sxg_buffer_t* dst) {
  const size_t offset = dst->size;
  // 4-byte blocks to 3-byte, allowing for padding chars;
  const EVP_ENCODE_BLOCK_T estimated_out_length = 3 * (src->size / 4);

  ASSERT_TRUE(sxg_buffer_resize(offset + estimated_out_length, dst));
  ASSERT_EQ(EVP_DecodeBlock(dst->data + offset, src->data, src->size), estimated_out_length);

  // EVP_DecodeBlock ignores padding, so we have to strip null bytes manually
  EVP_ENCODE_BLOCK_T actual_out_length = estimated_out_length;
  while(dst->data[actual_out_length-1] == 0) {
    actual_out_length--;
  }
  
  ASSERT_TRUE(sxg_buffer_resize(offset + actual_out_length, dst));
}
```
works for me with both OpenSSL and BoringSSL.

**Comment by twifkak** [comment]
OK, I uploaded a naive fix; please take a look. Allocates on the stack in BoringSSL, and on the heap in OpenSSL. (The latter doesn't seem to expose the struct impl in any .h in my include path.)

Thanks for the boringssl instructions. They didn't seem to work for me, though. Perhaps you can take a stab at #78? i.e. Adding a [Travis job](https://docs.travis-ci.com/user/build-matrix/#listing-individual-jobs) to build with BoringSSL. That way I can lean on the CI in the future, instead of my own inability to use cmake.

In particular, when I shoved this into `sxg_sig_test.cc`, I still got "hello from openssl":

```
#ifdef OPENSSL_IS_BORINGSSL
  std::cout << "hello from boringssl" << std::endl;
#else
  std::cout << "hello from openssl" << std::endl;
#endif
```

File: tests/sxg_sig_test.cc (hunk 1 above)
Comment (twifkak) [reply tests/sxg_sig_test.cc:64]: I think this might fail in the very rare case that the signature ends in a NUL byte? IIRC, that's how integer zero is encoded in DER.

We could count the padding chars at the end ourselves and know how many to strip. If my latest attempt doesn't work, I'll try that approach.

**Comment by cpapazian** [comment]
> In particular, when I shoved this into `sxg_sig_test.cc`, I still got "hello from openssl":
> 
> ```
> #ifdef OPENSSL_IS_BORINGSSL
>   std::cout << "hello from boringssl" << std::endl;
> #else
>   std::cout << "hello from openssl" << std::endl;
> #endif
> ```

it appears that this is happening b/c `${OPENSSL_INCLUDE_DIR}` isn't passed to target_include_directories for the test build

**Comment by twifkak** [comment]
Thanks @cpapazian, adding ${OPENSSL_INCLUDE_DIR} did the trick. Uploaded a fix. I'll go ahead and merge (pending checks) since it appears to be working in both openssl and boringssl now.

No longer blocked on #79 (though that change is still welcome for future PRs).
